server:
  port: 8761
#需要导入spring-boot-starter-security
#为Euraka server 添加一个认证，当访问localhost:8761会要求验证
management:
  endpoint:
    health: #健康检测 查看 http://localhost:8761/actuator/health
      show-details: always
spring:
  application:
    name: eureka-service
  security: #安全配置
    basic:
     enabled: true
    user:
      name: ${EUREKA_USERNAME:root}
      password: ${EUREKA_PASSWORD:root}
eureka:
  client:
    service-url:
      #erueka server的地址，/eureka
      defaultZone: ${EUREKA_DEFAULTZONE:http://root:root@127.0.0.1:8761/eureka}
    # 是否从eureka server注册，这里我们选择false
    fetch-registry: ${EUREKA_FETCH_REGISTRY:false}
    # 是否从eureka server 中拉取服务
    register-with-eureka: ${EUREKA_REGISTER_WITH_EUREKA:false}
  server:
    enable-self-preservation: ${EUREKA_ENABLE_SELF_PRESERVATION:false} # 关闭自我保护模式（缺省为打开）
